### ISSUE TITLE
npm install --global of the CLI on Windows fails because of permissions

### ISSUE THREAD

**Issue by Camille-SC** [thegetty/quire-docs#167]
```
C:\Users\nomadeDMPC>cd quire-cli

C:\Users\nomadeDMPC\quire-cli>npm install -g --rebuild
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated deflate-crc32-stream@0.1.2: module has been merged into crc32-stream
npm WARN checkPermissions Missing write access to C:\Users\nomadeDMPC\quire-cli\node_modules\anymatch\node_modules\arr-diff
npm WARN checkPermissions Missing write access to C:\Users\nomadeDMPC\quire-cli\node_modules\anymatch\node_modules\array-unique
npm WARN checkPermissions Missing write access to C:\Users\nomadeDMPC\quire-cli\node_modules\anymatch\node_modules\braces\node_modules\extend-shallow
npm WARN checkPermissions Missing write access to C:\Users\nomadeDMPC\quire-cli\node_modules\anymatch\node_modules\expand-brackets\node_modules\extend-shallow
```

The list continues and is way longer than that.

I'm a bit lost about what I can do.

cc @oncletom

**Comment by geealbers** [comment]
Sorry, I'm just now seeing this. @Camille-SC, if you're still having an issue, could you provide us the full output from your command line? Either here or by email. It would be useful for us to help diagnose the issue. Thanks!

**Comment by oncletom** [comment]
Hey @geealbers 👋 

I dive in the conversation because I was sitting next to @Camille-SC when this happened.

We made it work by uninstalling Node (that we downloaded from the official website), and by using [nvm-windows](https://github.com/coreybutler/nvm-windows) instead.

If I manage to get through gettypubs/quire-cli#21, maybe the `npm install --global github:gettypubs/quire-cli` would work without triggering this permissions error? It does seem to happen only when installing a global package from a local directory (to be confirmed).
