### ISSUE TITLE
Local preview running slow for quire-docs

### ISSUE THREAD

**Issue by Erin-Cecele** [thegetty/quire-docs#449]
Both @dimrkh and I have been experiencing painfully slow load times when previewing `quire-docs` on http://localhost:1313/. The homepage loads but I can't get beyond that without it timing out repeatedly. Changes also seem to take very long to show up. I did not have any issues while previewing `egypt-classical-world` so wondering if this is a docs specific issue. I'm on Chrome. @dimrkh What browser are you using?

**Comment by geealbers** [comment]
Yes. Here's something you can both try, and if it works for you on your machines, I think we'll make it a change in core Quire.

1. Use the "Go to Folder" option in Finder to open this directory: `/usr/local/lib/node_modules/@thegetty/quire-cli/bin/`
2. Open the index.js file in Atom and do a search to find this string: `join("config","environments","dev.yml")),"--watch")` and then add a comma and `"--disableFastRender"` to the end of the list there so that it reads: `join("config","environments","dev.yml")),"--watch","--disableFastRender")`.
3. Save the file and try running `quire preview` again.
4. Let me know if you see improvement.
